### ISSUE TITLE
Optimize page response speed

### ISSUE THREAD

**Issue by KidoPlay** [HoundSU/Mono#3]
## GFW block of china
Visitors from china can not access google and some other website due to block of GFW.
In file /php/head.php
Line: 65
```Php
<link href="https://fonts.googleapis.com/css?family=Lato:400,900" rel="stylesheet">
```
It will make the response to pages/posts extremly slow.
I have changed it to 
```Php
<link href="http://fonts.useso.com/css?family=Lato:400,900" rel="stylesheet">
```
to bypass the block.

However, I think you should create an extra file to store all external links,
it would be easy for users to modify and optimize page response time.

For example, I also changed these two links to provide faster services to Chinese visitors.
```Php
<link href="http://fonts.useso.com/css?family=Lato:400,900" rel="stylesheet">
<link href="https://cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

<!-- Custom Javascript -->
<script
			  src="//cdn.bootcss.com/jquery/2.2.3/jquery.min.js"
			  integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo="
			  crossorigin="anonymous">
</script>
```
But it took me some time to find what's slowing my website down,
it would be great if you could add one extra file to let users easily modify external links.

Thanks,

**Comment by HoundSU** [comment]
Thanks @KidoPlay, just did a push please look into it and reply what you think! 😄

**Comment by KidoPlay** [comment]
Tested and it worked perfectly.

Thanks for your awesome work.

**Comment by HoundSU** [comment]
Fantastic, If anything else comes up make sure to report it.
